package com.testing.edu.entity;

// Generated Oct 24, 2015 11:34:14 PM by Hibernate Tools 4.3.1

import com.testing.edu.entity.enumeration.AcademicStatus;
import com.testing.edu.entity.enumeration.Degree;
import lombok.EqualsAndHashCode;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Lecturers generated by hbm2java
 */
@Entity
@EqualsAndHashCode(of = "id")
@Table(name = "lecturers", catalog = "testing_system")
public class Lecturers implements java.io.Serializable {

	private Long id;
	private User user;
	private String lastName;
	private String firstName;
	private String middleName;
	private AcademicStatus academicStatus;
	private Degree degree;
	private Set<Subject> subjects = new HashSet<Subject>(0);

	public Lecturers() {
	}

	public Lecturers(User user) {
		this.user = user;
	}

	public Lecturers(String lastName, String firstName, String middleName, AcademicStatus academicStatus, Degree degree) {
		this.lastName = lastName;
		this.firstName = firstName;
		this.middleName = middleName;
		this.academicStatus = academicStatus;
		this.degree = degree;
	}

	public Lecturers(User user, String lastName, String firstName, String middleName, AcademicStatus academicStatus, Degree degree,
			Set<Subject> subjects) {
		this(lastName, firstName, middleName, academicStatus, degree);
		this.user = user;
		this.subjects = subjects;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_lecturers", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "last_name")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "first_name")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "middle_name")
	public String getMiddleName() {
		return middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "academic_status")
	@Enumerated(EnumType.STRING)
	public AcademicStatus getAcademicStatus() {
		return this.academicStatus;
	}

	public void setAcademicStatus(AcademicStatus academicStatus) {
		this.academicStatus = academicStatus;
	}

	@Column(name = "degree")
	@Enumerated(EnumType.STRING)
	public Degree getDegree() {
		return this.degree;
	}

	public void setDegree(Degree degree) {
		this.degree = degree;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "subject_has_lecturers", catalog = "testing_system", joinColumns = { @JoinColumn(name = "lecturers_id_lecturers", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "subject_id_subject", nullable = false, updatable = false) })
	public Set<Subject> getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Set<Subject> subjects) {
		this.subjects = subjects;
	}

}
