package com.testing.edu.entity;

// Generated Oct 24, 2015 11:34:14 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "testing_system")
public class User implements java.io.Serializable {

	private Integer id;
	private String username;
	private String email;
	private String password;
	private Boolean isEnabled;
	private String userRole;
	private Set<Lecturers> lecturerses = new HashSet<Lecturers>(0);
	private Set<Students> studentses = new HashSet<Students>(0);

	public User() {
	}

	public User(String username, String email, String password, Boolean isEnabled, String userRole,
			Set<Lecturers> lecturerses, Set<Students> studentses) {
		this.username = username;
		this.email = email;
		this.password = password;
		this.isEnabled = isEnabled;
		this.userRole = userRole;
		this.lecturerses = lecturerses;
		this.studentses = studentses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "is_enabled")
	public Boolean getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	@Column(name = "user_role")
	public String getUserRole() {
		return this.userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Lecturers> getLecturerses() {
		return this.lecturerses;
	}

	public void setLecturerses(Set<Lecturers> lecturerses) {
		this.lecturerses = lecturerses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Students> getStudentses() {
		return this.studentses;
	}

	public void setStudentses(Set<Students> studentses) {
		this.studentses = studentses;
	}

}
